backend:
  name: github
  repo: ChicagoDSA/chapter-website
  branch: prod
  site_domain: condescending-mestorf-98f7e3.netlify.app
media_folder: "images/"
public_folder: "images/"
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages/en" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "---" # Filename template, e.g., YYYY-MM-DD-title.md
    files:
      - label: "Afrosoc"
        name: "afrosoc"
        file: "_pages/en/afrosoc.md"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "hidden",
              default: "about",
            }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "about",
            }
          - { label: "Body", name: "body", widget: "markdown" }
